### ISSUE TITLE
About download link authorization

### ISSUE THREAD

**Issue by liushangke** [jc-audet/WOODS#11]
Dear author,

I'm doing OOD-related research and encountered a little problem when I try to download your datasets through scripts. Here is the error message. Could you please help me with the download link access authorization? Thank you.

Best,

Shangke
Northwestern University

Flags:
        data_path: /Users/shangke/Desktop/ideas_lab/WOODS/path/to/data
        dataset: ['PCL']
        mode: gdrive
Access denied with the following error:
        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
You may still be able to access the file from the browser:
         https://drive.google.com/uc?id=118DNxHpzeJwVTM22wzZhSiOuDsno0nay
Traceback (most recent call last):
  File "/opt/anaconda3/envs/d2l/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/d2l/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/shangke/Desktop/ideas_lab/WOODS/woods/scripts/download_datasets.py", line 32, in <module>
    download_pcl(flags.data_path, flags.mode)
  File "/Users/shangke/Desktop/ideas_lab/WOODS/woods/download.py", line 90, in download_pcl
    download_gdrive(archive_url, path, 'pcl.zip')
  File "/Users/shangke/Desktop/ideas_lab/WOODS/woods/download.py", line 16, in download_gdrive
    with zipfile.ZipFile(r, 'r') as zip_ref:
  File "/opt/anaconda3/envs/d2l/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/opt/anaconda3/envs/d2l/lib/python3.8/zipfile.py", line 1332, in _RealGetContents
    endrec = _EndRecData(fp)
  File "/opt/anaconda3/envs/d2l/lib/python3.8/zipfile.py", line 264, in _EndRecData
    fpin.seek(0, 2)
AttributeError: 'NoneType' object has no attribute 'seek'

**Comment by jc-audet** [comment]
hmm yeah looks like there is some issue with authorization. I will try to fix it, in the meantime you can try and use the academic torrent option of the download script!

**Comment by liushangke** [comment]
Thank you. And just to add one point, seem that the training script doesn't work with the  manually downloaded dataset. Somehow it can't handle extracted .h5 file. Looking forward to your update!

Best,

**Comment by ShifengXIE** [comment]
I meet the same problem. Please update it again. Thank you @jc-audet
